### ISSUE TITLE
Release 0.10.1 to PyPI

### ISSUE THREAD

**Issue by alhirzel** [Lightning-AI/utilities#217]
## 🐛 Bug

Version 0.10.1 does not appear at: <https://pypi.org/project/lightning-utilities/>

### Expected behavior

It would be awesome if 0.10.1 could get propagated to PyPI!

### Additional context

I maintain [a `PKGBUILD` for Arch Linux](https://aur.archlinux.org/packages/python-lightning-utilities) that uses PyPI as the source of the latest version of your software. Until the update is pushed to PyPI, I cannot easily update my script to use the latest version of your package.

**Comment by Borda** [comment]
Apologies, there was an action issue that I missed, it shall be live now...
https://pypi.org/project/lightning-utilities/0.10.1/

**Comment by alhirzel** [comment]
Thank you @Borda, for your prompt help and getting this fixed! My side is now updated too.
