### ISSUE TITLE
Integrate warnings and rank zero utilities

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/utilities#22]
## 🚀 Feature

Integrate https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/utilities/rank_zero.py and https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/utilities/warnings.py

**Comment by awaelchli** [comment]
These rank_zero utilities shouldn't go here. They rely on PL/Lite specific mechanics to set the rank and and parse it from env variables. It would not be very practical to have them in a different library.

**Comment by carmocca** [comment]
The only specific thing is the rank extraction, so we can just make that an argument to the utilities here.
