### ISSUE TITLE
pkg_build runs into error

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/utilities#274]
## 🐛 Bug

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.4/x64/bin/twine", line 5, in <module>
    from twine.__main__ import main
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/twine/__init__.py", line 43, in <module>
    __license__ = metadata["license"]
                  ~~~~~~~~^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
    raise KeyError(item)
KeyError: 'license'
```

https://github.com/Lightning-AI/LitServe/actions/runs/9670561173/job/26699429333?pr=155

### To Reproduce

Steps to reproduce the behavior...

<details>
  <summary><b>Code sample</b></summary>

</details>

### Additional context

<details>
  <summary><b>Environment details</b></summary>

- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

</details>

**Comment by Borda** [comment]
Fixed by #273

**Comment by aniketmaurya** [comment]
I just reran the CI and it still seem to fail though - https://github.com/Lightning-AI/LitServe/actions/runs/9670561173/job/26730663529?pr=155

**Comment by Borda** [comment]
> I just reran the CI and it still seem to fail though - https://github.com/Lightning-AI/LitServe/actions/runs/9670561173/job/26730663529?pr=155

Because you are still using old version, so use `main` or latest release
https://github.com/Lightning-AI/LitServe/blob/ee1a7b53772332a937bdb548277b28cc54ba16e0/.github/workflows/ci-checks.yml#L26
