### ISSUE TITLE
Add documentation to the rank_zero_only function

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/utilities#37]
## 📚 Documentation

Document that the rank_zero_only function only works as intended once the actual rank is set, i.e., `rank_zero_only.rank = x`. This needs to be handled by the application that uses this function.

**Comment by carmocca** [comment]
As an note: In the implementation here a better error is raised if not set: https://github.com/Lightning-AI/utilities/blob/fb2a8a0f0e249892cbc892d91f3e9e60b0de83a4/src/lightning_utilities/core/rank_zero.py#L18

**Comment by awaelchli** [comment]
Not needed if the error message is reliable.
