### ISSUE TITLE
Rename `lightning_utilities.dev` to `lightning_utilities.cli`

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/utilities#44]
## 🚀 Feature
See title.

### Motivation
`dev` sounds very ambiguous to me.

### Alternatives
- Keep as is.
- Rename it to a different name.

### Additional context
Since the cli subpackage will be used only in our CI, this issue shouldn't be highly prioritised.

**Comment by Borda** [comment]
make sense to me :)
