### ISSUE TITLE
Create `lightning_utilities.testing` subpackage

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/utilities#45]
## 🚀 Feature
Collect common classes, functions, e.g.

- [ ] `RunIf`: https://github.com/Lightning-AI/lightning/blob/95374440ce9b4f499f83b0e6b8cee0bc715aa18b/tests/tests_pytorch/helpers/runif.py#L55
- [ ] `no_warning_call`: https://github.com/Lightning-AI/lightning/blob/95374440ce9b4f499f83b0e6b8cee0bc715aa18b/tests/tests_pytorch/helpers/utils.py#L92
- [ ] ...

### Motivation
Prevents duplication across repositories.

**Comment by Borda** [comment]
@carmocca still thinking about having the `RunIf` as a prototype with some simple functionality which would be extended/inherit in particular projects like PL

**Comment by carmocca** [comment]
What simple functionality? Only `min_python` and `skip_windows` don't require any packages. And the code deduplication will be almost nothing because each repo will need to rewrite its own.

**Comment by carmocca** [comment]
I added https://github.com/Lightning-AI/utilities/commit/88bd877506353d7329e24172634c20ca2b50ff66 but haven't updated the projects to use it.

**Comment by Borda** [comment]
I found with cutting strategies and accelerators that I am always coping with GPU, standalone, min torch, etc.

**Comment by carmocca** [comment]
What's the issue with copying it? It's very simple infrastructure. If you wanted to share code, then it should be done through fabric or pytorch lightning, which do install torch
