### ISSUE TITLE
Add markdown link checker action

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/utilities#80]
## 🚀 Feature
Inspired by https://github.com/Lightning-AI/lightning/pull/16168 authored by @shenoynikhil, we can include the link checker in this repository, too, so that all our projects benefit from the GH action 🚀

### Pitch
Create a reusable workflow file `.github/workflows/check-md-links.yml` (or a better name).

**Comment by shenoynikhil** [comment]
I can take this up!
