### ISSUE TITLE
Introduce ModuleAvailableCache

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/utilities#85]
### Motivation

RequirementCache exists, but it is very general. It works for both modules as well as packages. It has a very strict check for requirements of a package. This check can fail **even if the package is actually importable successfully**, see example: https://github.com/Lightning-AI/lightning/issues/16464

In these cases, the `module_available` check is better suited for what we want to check. But it can only be called as a function, not as a cache like the RequirementCache.

### Pitch

Add `ModuleAvailableCache`, with a cache implementation like RequirementCache, but we will use the `module_available` function as as the check function.

### Alternatives

User has to resolve any package conflicts in their environment, even if they are harmless.

### Additional context

See https://github.com/Lightning-AI/lightning/issues/16464

**Comment by awaelchli** [comment]
cc @carmocca @Borda

**Comment by carmocca** [comment]
Sounds good to me
