### ISSUE TITLE
Define global action.yaml

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/utilities#93]
### Motivation

Seems that particular actions/workflows are not recognized by dependabot and so several of our repo/projects are still using the old version... On the other hand, pin `main` may have some overhead as we could introduce breaking changes and so broke the particular CI until it is aligned.

So the one global action would aggregate the suggested group of workflows: https://github.com/Lightning-AI/utilities/blob/main/.github/workflows/ci-use-checks.yaml
Also, we can consider based on input/parameter to tun some workflows off :chipmunk: 

### Pitch

allow dependabot to pick up whenever we make a new release

### Alternatives

switch to use `main` by default

### Additional context

see: https://docs.github.com/en/actions/creating-actions

**Comment by Borda** [comment]
Seem GH updated this case, and recently, new CICD versions were pocked by dependable...

**Comment by akihironitta** [comment]
@Borda I thought you somehow managed to make dependabot recognise our releases :) We can close this issue then?

**Comment by Borda** [comment]
> @Borda I thought you somehow managed to make dependabot recognise our releases :) We can close this issue then?

it was not me, so yeah, let's close it for now :)

**Comment by Borda** [comment]
on the other hand, having global we can have it on GH marketplace :)
